Move generated file ttrpc.rs to OUT_DIR
Got:
cargo publish --dry-run

error: failed to verify package tarball

Caused by:
  Source directory was modified by build.rs during cargo publish. Build scripts should not modify anything outside of OUT_DIR.
Added: /home/tim/project/ttrpc-rust/target/package/ttrpc-0.4.0/src/ttrpc.rs

This commit will resolve this issue.

Signed-off-by: Tim Zhang <tim@hyper.sh>